### ISSUE TITLE
Hey man! This is not safe to keep parameters.yml file in repo

### ISSUE THREAD

**Issue by athlonUA** [ProjetTutoreRVBC/ProjetTutore#2]
https://github.com/ProjetTutoreRVBC/ProjetTutore/blob/1ab8b3a6df89daf8383c9f2a13e1121fd2a521dc/app/config/parameters.yml

```
mysql -h dwarves.iut-fbleau.fr -u brassele -p

**Comment by athlonUA** [comment]
🔑

**Comment by projetphpsen** [comment]
Of course it is not !
It is just a small university project, so it's no big deal, we were amazed that someone managed to find our tiny project, even randomly ;)
But thanks for the tip ;)

Simon

**Comment by athlonUA** [comment]
👌

**Comment by athlonUA** [comment]
@projetphpsen
